# Generated by Django 4.1.6 on 2023-02-09 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_nat_id_nurse_doctor_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('name', models.CharField(max_length=220)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('status', models.CharField(max_length=150)),
                ('nat_id', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('disease_type', models.CharField(max_length=250)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('address', models.CharField(max_length=500)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_admin', to='users.admin')),
                ('doctor', models.ManyToManyField(related_name='doctor', to='users.doctor')),
                ('nurse', models.ManyToManyField(related_name='nurse', to='users.nurse')),
            ],
            options={
                'verbose_name': 'Patients',
                'verbose_name_plural': 'Patients',
                'db_table': 'Patients',
                'ordering': ['-date_joined'],
            },
        ),
    ]
