# Generated by Django 4.1.6 on 2023-02-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
